version: "3"
services:
  webapi8:
    image: webapp8:latest
    container_name: "webapp8"
    ports:
      - 8080:80
    environment:
      ASPNETCORE_URLS: "http://+:80"

  webapi6:
    image: webapp6:latest
    container_name: "webapp6"
    ports:
      - 8081:80
    environment:
      ASPNETCORE_URLS: "http://+:80"

